# Generated by Django 2.1.4 on 2018-12-31 05:24

from django.db import migrations, models
import serializer.storage


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_info',
            name='model_pic',
            field=models.ImageField(default='restapi/imagemodel', storage=serializer.storage.OverwriteStorage(), upload_to='restapi/imagemodel'),
        ),
    ]
