# Generated by Django 2.1.4 on 2018-12-30 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant_info',
            name='plant_type',
        ),
        migrations.AlterField(
            model_name='plant_info',
            name='scan_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_details', to='serializer.Scan'),
        ),
    ]
